---
title: "AURIN"
output: 
  html_document:
    keep_md: true
  
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#https://aurin.org.au/resources/aurin-apis/aurin-open-api-and-r/
#https://github.com/asiripanich/aurin

#install.packages("aurin")
#library(aurin)

#UPDATE 19.07 -> Aurin made them remove the aurin package, now it is called notaurin
remotes::install_github("asiripanich/notaurin")
library(notaurin)

#had to create new credentials 19.07 on the aurin new ADP website
notaurin::aur_register("mxmoe", "ageIu0jwbBvy8d1O")

#hmm this doesn't seem to be working: maybe go through the official aurin channel instead:https://aurin.org.au/resources/training/explore-r/


```

```{r}
#library(sf)
#library(httr)
#library(tidyverse)
#library(ows4R)
#install.packages('mapview')
#library(mapview)
#library(utils)
#### ------ Setup variables ------- #####
wfs_url <- "https://adp.aurin.org.au/geoserver/wfs"
user_name <- "mxmoe"
password <- "ageIu0jwbBvy8d1O"
#### ------ Define url ----- ####
url <- httr::parse_url(wfs_url)
url$hostname <- paste(user_name,":",password,"@",url$hostname, sep="")
adp_client <- WFSClient$new(url = wfs_url, user = user_name, pwd = password, serviceVersion = '2.0.0')


#hmm the below is not working either when it comes to the download/file function
#toilet data:
url$query <- list(service = "wfs",
version = "2.0.0", 
request = "GetFeature",
typeName = "datasource-AU_Govt_DSS-UoM_AURIN:national_public_toilets_2017",
srsName = "EPSG:4283") #had to update this
request <- build_url(url)
request
### ---- Download the data ---- ###
download.file(request, destfile = "./data_toilet.gml", mode='wb')
### ---- Read the data ---- ####
data <- read_sf("data_fire.gml")
```




```{r}
aur_browse()
meta<-notaurin::aur_meta() #hmm this isn't working now...

#public_toilets<-aur_get("aurin:datasource-UQ_ERG-UoM_AURIN_DB_public_toilets")
#19.07 let's use the 2017 data instead

public_toilets<-aur_get("aurin:datasource-AU_Govt_DSS-UoM_AURIN:national_public_toilets_2017")

state_polygons <- aur_get(open_api_id = "aurin:datasource-AU_Govt_ABS-UoM_AURIN_DB_GeoLevel_ste_2016_aust")
state_polygons <- state_polygons[state_polygons$state_code_2016 %in% 1:8, ]

```



```{r}
library(ggplot2)
ggplot(public_toilets) +
  geom_sf(data = state_polygons, fill = "antiquewhite") +
  geom_sf(alpha = 0.05, aes(color = status)) +
  labs(title = "Public toilets in Australia, 2017") +
  scale_color_brewer(palette = "Dark2") +
  theme_bw() +
  guides(colour = guide_legend(override.aes = list(alpha = 1))) +
  theme(panel.background = element_rect(fill = "aliceblue"))
```


```{r}
#RV zoom in on NSW specifically
library(tidyverse)
glimpse(state_polygons)

NSW_polygons<-state_polygons %>% filter(state_name_2016=="New South Wales")

glimpse(public_toilets)
NSW_toilets<-public_toilets %>% filter(state=="New South Wales")

NSW_toilets %>% count(isopen)
```



```{r}
NSW_plot<-ggplot(NSW_toilets) +
  geom_sf(data = NSW_polygons, fill = "antiquewhite") +
  geom_sf(alpha = 0.4, aes(color = status, shape=isopen, label=name)) +
  labs(title = "Public toilets in Australia, 2017") +
  scale_color_brewer(palette = "Dark2") +
  theme_bw() +
  guides(colour = guide_legend(override.aes = list(alpha = 1))) +
  theme(panel.background = element_rect(fill = "aliceblue"))
```

```{r}
#zoom further into Sydney North shore

Sydney_plot<-NSW_plot + 
    coord_sf(xlim = c(151.05, 151.3), ylim = c(-33.75, -33.87), expand = FALSE)

Sydney_plotly<-plotly::ggplotly(Sydney_plot)


```

```{r}
htmlwidgets::saveWidget(Sydney_plotly, "Sydney_plotly.html")
#share to my plotly account
# set plotly user name
Sys.setenv("plotly_username"="RachelPlotly")
# set plotly API key
Sys.setenv("plotly_api_key"="KkKdjsu9KGx5p8qyqBP7")
plotly::plotly_POST(Sydney_plotly, sharing="public")
```



Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
